valory-xyz/docs

.gitmodules

chore/remove open-aea submodule

chore/remove open-aea submodule

---

Makefile

fix: open-autonomy submodule version

fix: open-autonomy submodule version

---

.markdownlint.json

Release v0.8.0

---

HISTORY.md

Prepare for release v0.8.0.post1

---

HISTORY.md

Update submodules
Update HISTORY.md

Prepare for v0.8.0.post2

---

HISTORY.md

Prepare for release v0.8.0.post3

Prepare for release v0.8.0.post3

---

HISTORY.md
docs/index.md
docs/products/index.md
docs/protocol/index.md

Prepare for release v0.8.0.post4

---

HISTORY.md

Prepare for release v0.8.0.post5

---

docs/protocol/contract_addresses.md
mkdocs.yml

Add contract addresses

---

scripts/check_doc_links.py

Doc links linter

---

HISTORY.md

Prepare for release v0.9.1.post2

---

HISTORY.md

Lightweight documentation update on hashes on the submodule Open Autonomy, file set_up.md

Update submodule & Prepare for release 0.10.0.post2

---

Makefile
mkdocs.yml

Minor housekeeping additions

---

HISTORY.md

Prepare for release v0.10.1

---

HISTORY.md

**Please, each PO approve this PR after confirming that for the submodule linked to their repos:**
1. The submodule update is pointing to the intended commit, which should be the latest tag/release.
2. **The release workflow of the corresponding repository has finished successfully (green icon).**
3. To the best of your knowledge, the public-facing tutorial in the submodule (`<submodule_folder>/docs/index.md`) is up to date. In particular, you agree with the instructions in the section "Demo".
4. You have replicated the instructions exactly as described in the public-facing tutorial (with the exact options, hash values, command line parameters, private keys, etc. described there), in a clean virtual environment, and it has worked. Also:
a. an external user is able to replicate the demo …

Update submodules & Prepare for release v0.10.2

---

Dockerfile
poetry.lock

- Fixed Dockerfile
- Updated Poetry dependency lock

Fix Dockerfile & Prepare for release v0.10.2

---

HISTORY.md

Prepare for release v0.10.3

---

README.md

Update deployment info

---

HISTORY.md

Prepare for release v0.10.5

---

HISTORY.md

Prepare for release v0.10.7

---

HISTORY.md
poetry.lock
pyproject.toml

- Updated HISTORY.md
- Updated dependencies

Prepare for release v0.10.10.post1

---

HISTORY.md

Prepare for release v0.11.1

---

HISTORY.md

**Please, each PO approve this PR after confirming that for the submodule linked to their repos:**
1. The submodule update is pointing to the intended commit, which should be the latest tag/release.
2. **The release workflow of the corresponding repository has finished successfully (green icon).**
3. To the best of your knowledge, the public-facing tutorial in the submodule (`<submodule_folder>/docs/index.md`) is up to date. In particular, you agree with the instructions in the section "Demo".
4. If a specific version of a dependency is required, it is made explicit in the section "Demo". In particular, the Open Autonomy version used by the toolkit should be explicit in the section "Demo".
5. You have replicated the instructions exactly as described in the section "Demo" (with the exact …

Update submodules & Prepare for release v0.12.1.post4

---

scripts/check_doc_links.py

https://github.com/valory-xyz/open-autonomy/pull/2128

Use branch with latest hello-world hash

---

docs/protocol/index.md
docs/protocol/technical_overview.md

Fix addresses

---

HISTORY.md

Release v0.14.6.post2

---

README.md
docs/javascripts/dynamic-hash.js
mkdocs.yml

Dynamic hash on docs - mainly for quickstart.

Dynamic hash on docs

---

.spelling
Dockerfile
HISTORY.md
docs/protocol/life_cycle_of_a_service.md
docs/protocol/mint_packages_nfts.md

**Please, each PO approve this PR after confirming that for the submodule linked to their repos:**
1. The submodule update is pointing to the intended commit, which should be the latest tag/release.
2. **The release workflow of the corresponding repository has finished successfully (green icon).**
3. To the best of your knowledge, the public-facing tutorial in the submodule (`<submodule_folder>/docs/index.md`) is up to date. In particular, you agree with the instructions in the section "Demo".
4. If a specific version of a dependency is required, it is made explicit in the section "Demo". In particular, the Open Autonomy version used by the toolkit should be explicit in the section "Demo".
5. You have replicated the instructions exactly as described in the section "Demo" (with the exact …

Update submodules & Release v0.17.0

---

.github/workflows/docs.yml
HISTORY.md
docs/mech-client/index.md
docs/mech-tool/index.md
docs/olas-sdk/index.md
mkdocs.yml
scripts/__init__.py
scripts/check_copyright.py
scripts/check_doc_links.py

Update open-autonomy submodule

Update submodules & Release PR

---

docs/mech-tool/index.md

Very small PR to address some typos

small typo

---

.spelling
docs/olas-sdk/index.md
mkdocs.yml

This PR adds the instructions for Olas SDK

Add Olas SDK instructions

---

HISTORY.md
docs/olas-sdk/index.md

Prepare for release v0.16.4

---

HISTORY.md

Prepare for release v0.18.11

---

HISTORY.md

Prepare for release v0.19.0.post1

Prepare for release v0.19.0.post1

---

.github/workflows/docs.yml
Makefile
docs/demos/price-oracle/index.md
docs/products/index.md
scripts/check_submodule_release_updates.py
tox.ini

Fix: Add PR action to check submodule versions
